fn main() {
    // cargo-odra sets ODRA_MODULE=<StructName> before calling cargo build.
    // We translate it to a rustc cfg flag so that the #[cfg(odra_module = "X")]
    // blocks generated by #[odra::module] proc-macro are compiled in.
    println!("cargo:rerun-if-env-changed=ODRA_MODULE");
    if let Ok(module) = std::env::var("ODRA_MODULE") {
        println!("cargo:rustc-cfg=odra_module=\"{}\"", module);
    }
}
